"""Offence severity weights for Parking Impact Index (PII)."""

SEVERITY_WEIGHTS: dict[str, float] = {
    "PARKING IN A MAIN ROAD": 1.0,
    "DOUBLE PARKING": 0.95,
    "PARKING NEAR ROAD CROSSING": 0.9,
    "PARKING NEAR TRAFFIC LIGHT OR ZEBRA CROSS": 0.9,
    "PARKING OPPOSITE TO ANOTHER PARKED VEHICLE": 0.85,
    "PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC": 0.75,
    "WRONG PARKING": 0.7,
    "NO PARKING": 0.65,
    "PARKING ON FOOTPATH": 0.6,
    "PARKING OTHER THAN BUS STOP": 0.5,
    "DEFECTIVE NUMBER PLATE": 0.4,
    "REFUSE TO GO FOR HIRE": 0.4,
    "DEMANDING EXCESS FARE": 0.4,
    "USING BLACK FILM/OTHER MATERIALS": 0.35,
    "WITHOUT SIDE MIRROR": 0.3,
    "H T V PROHIBITED": 0.3,
    "OBSTRUCTING DRIVER": 0.3,
    "AGAINST ONE WAY/NO ENTRY": 0.3,
    "FAIL TO USE SAFETY BELTS": 0.2,
    "VIOLATING LANE DISIPLINE": 0.2,
}

OFFENCE_CODE_MAP: dict[int, str] = {
    107: "PARKING IN A MAIN ROAD",
    109: "DOUBLE PARKING",
    104: "PARKING NEAR ROAD CROSSING",
    106: "PARKING NEAR TRAFFIC LIGHT OR ZEBRA CROSS",
    108: "PARKING OPPOSITE TO ANOTHER PARKED VEHICLE",
    111: "PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC",
    112: "WRONG PARKING",
    113: "NO PARKING",
    105: "PARKING ON FOOTPATH",
    139: "PARKING OTHER THAN BUS STOP",
    116: "DEFECTIVE NUMBER PLATE",
    124: "REFUSE TO GO FOR HIRE",
    125: "DEMANDING EXCESS FARE",
    133: "USING BLACK FILM/OTHER MATERIALS",
    144: "WITHOUT SIDE MIRROR",
}

CARRIAGEWAY_THRESHOLD = 0.85
HEAVY_VEHICLE_TYPES = {
    "CAR",
    "MAXI-CAB",
    "LGV",
    "HGV",
    "BUS (BMTC/KSRTC)",
    "PRIVATE BUS",
    "TOURIST BUS",
    "TANKER",
    "LORRY/GOODS VEHICLE",
    "VAN",
    "TEMPO",
}


def get_severity(label: str) -> float:
    return SEVERITY_WEIGHTS.get(label.strip().upper(), 0.5)


def is_carriageway_blocking(label: str) -> bool:
    return get_severity(label) >= CARRIAGEWAY_THRESHOLD
